In [8]:
#1 – Liste Metotları

notlar = [85, 92, 76, 92, 100, 76, 85, 92]
x = set(notlar)
liste = list(x)
print(liste)
print(min(liste))
print(max(liste))
liste.sort()
print(liste)

[100, 92, 85, 76]
76
100
[76, 85, 92, 100]


In [14]:
# 2 – Sayılar
def armstrong_mu(sayi):
    toplam = 0
    for basamak in str(sayi):
        toplam += int(basamak) ** 3
    return toplam == sayi

print(armstrong_mu(153)) 
print(armstrong_mu(370)) 
print(armstrong_mu(123)) 

True
True
False


In [37]:
# 3 – Kümeler

A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
print(A.intersection(B))
print(A.difference(B))
(A.update(B))
liste = list(A)
print(sorted(liste))

{'SQL', 'Python'}
{'R', 'Java'}
['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


In [40]:
# 4 – Modüller

import random
import math 

sayilar = [random.randint(1, 100) for _ in range(10)]
print("Sayılar:", sayilar)

ortalama = sum(sayilar) / len(sayilar)
toplam_fark_kareleri = sum((x - ortalama) ** 2 for x in sayilar)
std_sapma = math.sqrt(toplam_fark_kareleri / (len(sayilar) - 1))  # Örneklem std

print("Ortalama:", ortalama)
print("Standart Sapma:", std_sapma)


Sayılar: [16, 97, 64, 6, 60, 95, 47, 85, 14, 80]
Ortalama: 56.4
Standart Sapma: 34.38733617029514


In [43]:
# 5 – Fonksiyonlar

def kelime_analizi(metin):
    kelimeler = metin.split()
    toplam_kelime = len(kelimeler)
    en_uzun = max(kelimeler, key=len)
    kelime_sayaci = {}
    
    for kelime in kelimeler:
        if kelime in kelime_sayaci:
            kelime_sayaci[kelime] += 1
        else:
            kelime_sayaci[kelime] = 1
    
    en_sik = max(kelime_sayaci, key=kelime_sayaci.get)
    return toplam_kelime, en_uzun, en_sik

metin = input(str("Cümlenizi Giriniz: "))
toplam, uzun, sik = kelime_analizi(metin)

print("Toplam kelime sayısı:", toplam)
print("En uzun kelime:", uzun)
print("En sık geçen kelime:", sik)


Cümlenizi Giriniz:  Python öğrenmek çok eğlenceli ve öğretici bir süreçtir. Python ile projeler yapmak keyiflidir.


Toplam kelime sayısı: 13
En uzun kelime: keyiflidir.
En sık geçen kelime: Python


In [49]:
# 6 – Gömülü Fonksiyonlar

sayilar = [5, 12, 7, 18, 24, 3, 16]
ciftler = filter(lambda x: x % 2 == 0, sayilar)
kareler = map(lambda x: x ** 2, ciftler)
sirali = sorted(kareler, reverse=True)

print(sirali)

[576, 324, 256, 144]


In [51]:
# 8 – Metodlar

def rakam_toplami(metin):
    toplam = 0
    for karakter in metin:
        if karakter.isdigit():         
            toplam += int(karakter)     
    return toplam

metin = input(str("Bir Cümle Giriniz: "))
print(rakam_toplami(metin)) 


Bir Cümle Giriniz:  abc12def3


6


In [52]:
# 9 – (Ekstra) Numpy 1

import numpy as np

dizi = np.random.randint(0, 51, size=10)
print("Dizi:", dizi)
ortalama = np.mean(dizi)
std_sapma = np.std(dizi)
en_buyuk = np.max(dizi)

print("Ortalama:", ortalama)
print("Standart Sapma:", std_sapma)
print("En büyük değer:", en_buyuk)


Dizi: [40 39 18 12 40 33 29 35 12 47]
Ortalama: 30.5
Standart Sapma: 11.80889495253472
En büyük değer: 47


In [53]:
# 10 – (Ekstra) Numpy 2

import numpy as np

matris = np.random.rand(5, 5)
print("Orijinal Matris:\n", matris)
sutun_ortalamalari = np.mean(matris, axis=0)
print("\nSütun Ortalamaları:", sutun_ortalamalari)
binary_matris = (matris > 0.5).astype(int)
print("\nBinary Matris:\n", binary_matris)


Orijinal Matris:
 [[0.16482337 0.07813543 0.47045521 0.22268683 0.50594826]
 [0.20903826 0.41697848 0.75351868 0.35073273 0.78059582]
 [0.63583184 0.98760696 0.8674502  0.90316072 0.23375255]
 [0.73535112 0.66232733 0.71956008 0.52625791 0.68134509]
 [0.31001552 0.34324229 0.76288643 0.07117568 0.17456219]]

Sütun Ortalamaları: [0.41101202 0.4976581  0.71477412 0.41480277 0.47524078]

Binary Matris:
 [[0 0 0 0 1]
 [0 0 1 0 1]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [0 0 1 0 0]]
